version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: iha_uretim_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=iha_uretim_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  frontend:
      build: ./client
      container_name: iha_frontend
      volumes:
        - ./client:/app
        - /app/node_modules
      ports:
        - "3000:3000"
      depends_on:
        - web
      environment:
        - REACT_APP_API_URL=http://localhost:8001/api
        - NODE_OPTIONS=--openssl-legacy-provider


volumes:
  postgres_data: