# Generated by Django 5.1.6 on 2025-03-01 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircrafts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcaDurumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(choices=[('KULLANILABILIR', 'Kullanılabilir'), ('KULLANILIYOR', 'Kullanılıyor'), ('KUSURLU', 'Kusurlu'), ('GERI_DONUSUM', 'Geri Dönüşüm')], max_length=50, unique=True, verbose_name='Durum Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Parça Durumu',
                'verbose_name_plural': 'Parça Durumları',
                'db_table': 'parca_durumlari',
            },
        ),
        migrations.CreateModel(
            name='ParcaTipi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(choices=[('KANAT', 'Kanat'), ('GOVDE', 'Gövde'), ('KUYRUK', 'Kuyruk'), ('AVIYONIK', 'Aviyonik')], max_length=50, unique=True, verbose_name='Parça Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Parça Tipi',
                'verbose_name_plural': 'Parça Tipleri',
                'db_table': 'parca_tipleri',
            },
        ),
        migrations.CreateModel(
            name='Parca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seri_no', models.CharField(max_length=100, unique=True, verbose_name='Seri No')),
                ('uretim_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Üretim Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('ucak_tipi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aircrafts.ucaktipi', verbose_name='Uçak Tipi')),
                ('durum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parts.parcadurumu', verbose_name='Durum')),
                ('parca_tipi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parts.parcatipi', verbose_name='Parça Tipi')),
            ],
            options={
                'verbose_name': 'Parça',
                'verbose_name_plural': 'Parçalar',
                'db_table': 'parcalar',
                'indexes': [models.Index(fields=['parca_tipi', 'ucak_tipi', 'durum'], name='parcalar_parca_t_440cb5_idx')],
            },
        ),
    ]
