# Generated by Django 5.1.6 on 2025-03-01 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcatipi',
            name='sorumlu_takim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.takim', verbose_name='Sorumlu Takım'),
        ),
    ]
