# Generated by Django 5.1.6 on 2025-03-01 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0002_initial'),
        ('parts', '0002_parcatipi_sorumlu_takim'),
    ]

    operations = [
        migrations.AddField(
            model_name='parca',
            name='kullanilan_ucak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kullanilan_parcalar', to='aircrafts.ucak', verbose_name='Kullanılan Uçak'),
        ),
    ]
