# Generated by Django 5.1.6 on 2025-03-01 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_parca_kullanilan_ucak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parca',
            name='kullanilan_ucak',
        ),
    ]
