# Generated by Django 5.1.6 on 2025-02-27 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircrafts', '0002_initial'),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envanter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mevcut_adet', models.PositiveIntegerField(default=0, verbose_name='Mevcut Adet')),
                ('minimum_esik', models.PositiveIntegerField(default=5, verbose_name='Minimum Eşik')),
                ('son_guncelleme', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('parca_tipi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.parcatipi', verbose_name='Parça Tipi')),
                ('ucak_tipi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircrafts.ucaktipi', verbose_name='Uçak Tipi')),
            ],
            options={
                'verbose_name': 'Envanter',
                'verbose_name_plural': 'Envanter',
                'db_table': 'envanter',
                'unique_together': {('parca_tipi', 'ucak_tipi')},
            },
        ),
    ]
