# Generated by Django 5.1.6 on 2025-03-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParcaKullanimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanim_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kullanım Tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Parça Kullanımı',
                'verbose_name_plural': 'Parça Kullanımları',
                'db_table': 'parca_kullanimlari',
            },
        ),
        migrations.CreateModel(
            name='Ucak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seri_no', models.CharField(max_length=100, unique=True, verbose_name='Seri No')),
                ('montaj_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Montaj Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
            ],
            options={
                'verbose_name': 'Uçak',
                'verbose_name_plural': 'Uçaklar',
                'db_table': 'ucaklar',
            },
        ),
        migrations.CreateModel(
            name='UcakDurumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(choices=[('MONTAJ', 'Montajda'), ('TAMAMLANDI', 'Tamamlandı'), ('TESLIM_EDILDI', 'Teslim Edildi')], max_length=50, unique=True, verbose_name='Durum Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Uçak Durumu',
                'verbose_name_plural': 'Uçak Durumları',
                'db_table': 'ucak_durumlari',
            },
        ),
        migrations.CreateModel(
            name='UcakTipi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=20, unique=True, verbose_name='Model Kodu')),
                ('ad', models.CharField(max_length=100, verbose_name='Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Uçak Tipi',
                'verbose_name_plural': 'Uçak Tipleri',
                'db_table': 'ucak_tipleri',
            },
        ),
    ]
