# Generated by Django 5.1.6 on 2025-03-01 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircrafts', '0001_initial'),
        ('parts', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcakullanimi',
            name='parca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parts.parca', verbose_name='Parça'),
        ),
        migrations.AddField(
            model_name='ucak',
            name='montaj_yapan_takim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.takim', verbose_name='Montaj Yapan Takım'),
        ),
        migrations.AddField(
            model_name='ucak',
            name='parcalar',
            field=models.ManyToManyField(related_name='kullanildigi_ucaklar', through='aircrafts.ParcaKullanimi', to='parts.parca'),
        ),
        migrations.AddField(
            model_name='parcakullanimi',
            name='ucak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aircrafts.ucak', verbose_name='Uçak'),
        ),
        migrations.AddField(
            model_name='ucak',
            name='durum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aircrafts.ucakdurumu', verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='ucak',
            name='ucak_tipi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aircrafts.ucaktipi', verbose_name='Uçak Tipi'),
        ),
        migrations.AlterUniqueTogether(
            name='parcakullanimi',
            unique_together={('parca', 'aktif')},
        ),
    ]
