# Generated by Django 5.1.6 on 2025-02-27 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciTakim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katilma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Katılma Tarihi')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Takım',
                'verbose_name_plural': 'Kullanıcı Takımlar',
                'db_table': 'kullanici_takimlar',
            },
        ),
        migrations.CreateModel(
            name='Takim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Takım Adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('montaj_yetkisi', models.BooleanField(default=False, verbose_name='Montaj Yetkisi')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('uyeler', models.ManyToManyField(related_name='takimlar', through='teams.KullaniciTakim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Takım',
                'verbose_name_plural': 'Takımlar',
                'db_table': 'takimlar',
            },
        ),
        migrations.AddField(
            model_name='kullanicitakim',
            name='takim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.takim', verbose_name='Takım'),
        ),
        migrations.AlterUniqueTogether(
            name='kullanicitakim',
            unique_together={('kullanici', 'takim')},
        ),
    ]
